### model
model_name_or_path: Qwen/Qwen3-VL-4B-Instruct
image_max_pixels: 131072
video_max_pixels: 8192
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: rm_think_train  # rm_think   alpaca_en_demo
template: qwen3_vl_nothink
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 1
dataloader_num_workers: 0

### output
output_dir: saves/qwen3vl-4b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true
resume_from_checkpoint: null

## eval
eval_dataset: rm_think_eval
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 50
